catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include(('django.contrib.auth.urls'))),
    path('',include(('main_app.urls'))),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('about/', views.about, name="about"),
    path('cats/', views.cats_index, name="index"),
    path('cats/<int:cat_id>', views.cats_detail, name="detail"),
    # CBV's
    path('cats/create', views.CatCreate.as_view(), name="create"),
    path('cats/<int:pk>/update', views.CatUpdate.as_view(), name="cats_update"),
    path('cats/<int:pk>/delete', views.CatDelete.as_view(), name="cats_delete"),
    # Manual Path
    path('cats/<int:cat_id>/add_feeding', views.add_feeding, name="add_feeding"),
    
    # toys
    path('toys/', views.ToyList.as_view(),name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(),name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(),name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(),name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(),name='toys_delete'),
    
    path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('cats/<int:cat_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
    
    # Signup
    path('accounts/signup', views.signup, name='signup'),
]  

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User 

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Launch'),
    ('D', 'Dinner'),
)

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(this):
        return this.name

    def get_absolute_url(this):
        return reverse("toys_detail", kwargs={"pk":this.id})

# Create your models here.
class Cat(models.Model):
    name = models.CharField(max_length=100) # input text box 
    breed = models.CharField(max_length=100) # input text box 
    description = models.TextField(max_length=250) # input Text area 
    age = models.IntegerField() # input number
    image = models.ImageField(upload_to='main_app/static/uploads/', default="")
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(this):
        return this.name 

    def get_absolute_url(this):
        return reverse("detail",kwargs={"cat_id": this.id})

    def is_fed(this):
        return this.feeding_set.filter(date=date.today()).count() >= len(MEALS)

class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(this): 
        return f"{this.cat.name} {this.get_meal_display()} on {this.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Cat, Feeding, Toy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import FeedingForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def home(request):
    return render(request, 'home.html') 
    

def about(request):
    return render(request, 'about.html')

@login_required
def cats_index(request): 
    # SELECT * FROM 'main_app_cat'
    cats = Cat.objects.all()
    return render(request, 'cats/index.html', {'cats': cats})

@login_required
def cats_detail(request, cat_id): 
    cat = Cat.objects.get(id=cat_id)
    toys_cat_dosnt_have = Toy.objects.exclude(id__in = cat.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'cats/cats_detail.html', {
        'cat': cat,
        "feeding_form":feeding_form,
        "toys":toys_cat_dosnt_have
    })

@login_required
def add_feeding(request, cat_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False) # means just keep the changes on the code side no the database
        new_feeding.cat_id = cat_id
        new_feeding.save() # Actually changing the database
    feedings = Feeding.objects.filter(cat_id=cat_id)
    return redirect('detail', cat_id=cat_id)

class CatCreate(LoginRequiredMixin ,CreateView):
    model = Cat
    fields = ["name", "breed", "description", "age", "image"]
    success_url = '/cats/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CatUpdate(LoginRequiredMixin ,UpdateView):
    model = Cat
    fields = [ "breed", "description", "age"]

class CatDelete(LoginRequiredMixin ,DeleteView):
    model = Cat
    success_url = '/cats/'

# Toys views
class ToyDetail(LoginRequiredMixin ,DetailView): # model_detail.html
    model = Toy

class ToyList(LoginRequiredMixin ,ListView): # model_list.html
    model = Toy

class ToyCreate(LoginRequiredMixin ,CreateView): # model_form.html
    model = Toy
    fields = "__all__"

class ToyUpdate(LoginRequiredMixin ,UpdateView): # model_form.html
    model = Toy
    fields = ['name','color']

class ToyDelete(LoginRequiredMixin ,DeleteView): # model_delete.html
    model = Toy
    success_url = '/toys/'

@login_required
def assoc_toy(request,cat_id,toy_id):
    Cat.objects.get(id=cat_id).toys.add(toy_id)
    return redirect('detail', cat_id=cat_id)


@login_required
def unassoc_toy(request,cat_id,toy_id):
    Cat.objects.get(id=cat_id).toys.remove(toy_id)
    return redirect('detail', cat_id=cat_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html'%} {% block content %}
<h1>I am in need for courses. manaf said</h1>
<hr />
<p>LOOOOL</p>

{% endblock %}

main_app/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cat Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="right brand-logo">&nbsp;&nbsp;Cat Collector</a>
            </li>
          </ul>
          
            <li>
              {% if not user.is_authenticated %}
              <a href="{% url 'about'%}">About</a>
              <a href="{% url 'login'%}">Login</a>
              <a href="{% url 'signup'%}">Signup</a>
              {% else%}
              <a href="{% url 'index' %}">Cats</a>
              <a href="{% url 'create'%}">Create a cat</a>
              
              <a href="{% url 'toys_create' %}">Create a toy</a>
              <a href="{% url 'toys_index'%}">All toys</a>
              <form action="{% url 'logout'%}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
              </form>
            </li>

            {% endif %}


          
        </div>
      </nav>
    </header>
    <main class="container">
      {% block content %}
      {% endblock %}
    </main>

    <footer class="page-footer">
      <div class="right">
        All Rights Rsserved, &copy; 2025 Cat Collector &nbsp; 
      </div>
    </footer>
  </body>
</html>

main_app/templates/cats/cats_detail.html
{% extends 'base.html' %} {% block content %}

{%load static%}
<h1>Cat List</h1>


<div class="card indexCard">
  <div class="card-content">
    <a href="/cats/{{cat.id}}">View</a>
    <span class="card-title">{{cat.name}}</span>
    <p>Breed: {{cat.breed}}</p>
    <p>Description: {{cat.description}}</p>
    {%if cat.age > 0 %}
    <p>Age: {{cat.age}}</p>
    {% else%}
    <p>Age: Kitten</p>
    {% endif %}
  </div>
    <img src="{% static cat.image|cut:'main_app/static/'%}" />
    <a href="{% url 'cats_delete' cat.id %}" class="btn" >Delete</a>
    <a href="{% url 'cats_update' cat.id %}" class="btn">Edit</a>
  </div>

  <div>
    <form action="{% url 'add_feeding' cat.id %}" method="post">
      {% csrf_token %}
      {{feeding_form.as_p}}
      <input type="submit" name="Add Feeding" class="btn">
    </form>
  </div>
  <table class="striped">
    {% for feeding in cat.feeding_set.all %}
  
      <tr>
        <td>{{feeding.date}}</td>
        <td>{{feeding.get_meal_display}}</td>
      </tr>
    {% endfor %}
  </table>

  {% if cat.is_fed %}
    <h5>Enough feeding man</h5>
  {% endif %}

  <hr>

  <div class="row">
    <div class="col s6">
      <h3>{{cat.name}}'s Toys</h3>
      {% if cat.toys.count %}
        {% for toy in cat.toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{toy.color}}">{{toy.color}}</span>{{toy.name}}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'unassoc_toy' cat.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
          </div>
        {% endfor %}
        {% else %}
        <h5>No Toys: </h5>
      {% endif %}
          <div class="col s6">
            <h3>Available Toys</h3>
            {% if toys.count %}  
              {% for toy in toys.all %}
                <div class="card">
                  <div class="card-content">
                    <span class="card-title">
                      A <span style="color: {{toy.color}}">{{toy.color}}</span>{{toy.name}}
                    </span>
                  </div>
                  <div class="card-action">
                    <form action="{% url 'assoc_toy' cat.id toy.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn">Add</button>
                    </form>
                  </div>

                </div>
              {% endfor %}
            {% else %}
              <h5>{{cat.name}} Already has all the toys available</h5>
            {% endif %}
          </div>
    </div>
  </div>



  <script>
    let dateEl = document.querySelector("#id_date")
    M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  let selectEl = document.querySelector("#id_meal")
  M.FormSelect.init(selectEl)
  </script>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

{%load static%}
<h1>Cat List</h1>

{% for cat in cats %}
<div class="card indexCard">
  <div class="card-content">
    <a href="{% url 'detail' cat.id%}">View</a>
    <span class="card-title">{{cat.name}}</span>
    <p>Breed: {{cat.breed}}</p>
    <p>Description: {{cat.description}}</p>
    {%if cat.age > 0 %}
    <p>Age: {{cat.age}}</p>
    {% else%}
    <p>Age: Kitten</p>
    {% endif %}
  </div>
    <img src="{% static cat.image|cut:'main_app/static/'%}" />
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html'%} {% block content %}
<h1>This is a home page</h1>
<hr />
<p>Hi, I am yousif, a Django developer.</p>

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends  'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span class="teal-test">{{ object.name }}</span>?</h4>

  <form method="post">
    {% csrf_token %}
    <input type="submit" value="yes - Delete!" id="btn">
    <a href="{% url 'detail' cat.id%}">Cancel</a>
  </form>


  {% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html'%}

<!-- Comment-->
{% block content %}


{% if object %}
  <h1>Edit <span class="teal-test"{{object.name}}></span> </h1>
{% else %}
  <h1>Add Cat</h1>
{% endif %} 




<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
<table>
  {{form.as_table}}
</table>
  <input type="submit" value="Submit !" calss="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Toy</h1>
  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Toy Details</h1>
<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}
{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Toy List</h1>
{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}
{% endblock %}